---
title: "Lab 03"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 1: Read the data

```{r}
library(data.table)

# only download if we haven't
if(!file.exists("met_all.gz")) {
  download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz", "met_all.gz", method="libcurl", timeout = 60)
}
met <- data.table::fread("met_all.gz")

```

## Step 2: Checking dimensions

```{r}
dim(met)
head(met)
tail(met)
str(met)
```

## Step 3: Take closer look at key variables

```{r}
table(met$year)
table(met$day)
table(met$hour)
```

```{r}
summary(met$temp)
summary(met$elev)
summary(met$wind.sp)
```

Updating NAs in elevation

```{r}
met$elev[met$elev==9999.0] <- NA
#met[elev ==9999.0, elev :=NA]
summary(met$elev)
```

The highest weather station is at `r max(met$elev, na.rm = TRUE)`.

Now fix the temperature!

```{r}
met <- met[temp>-15][order(temp)]
summary(met[,.(lat, lon, wind.sp, temp, elev)])
```

## Step 4: Calculate summary statistics

```{r}
met[elev==max(elev,na.rm = TRUE)][, summary(wind.sp)]
```

```{r}
met[elev == max(elev,na.rm = TRUE),.(
  temp_wind = cor (temp, wind.sp, use = "complete"),
  temp_hour = cor (temp, hour, use = "complete"),
  temp_day = cor (temp, day, use = "complete"),
  wind_day = cor (wind.sp, day, use = "complete"),
  wind_hour = cor (wind.sp, hour, use = "complete")
)]
```


## Step 7: Exploratory graphs

```{r}
hist(met$elev, breaks=100)
```

